### ISSUE TITLE
Option to paste? Also, option to see how many double spaces were removed?

### ISSUE THREAD

**Issue by Stickyhavr** [Stephen-Lon/Alfred-workflow-double-space-to-single-space#1]
Hello,
I see you're up to more Alfred workflows. :-) This one is also quite helpful for me; however, I have a few suggestions.

1) When the action was triggered by selected text, it would be great to have the option to paste/insert directly.  Perhaps in that case, it would be wise to copy the original text into the clipboard just in case something goes awry?

2) Whether or not you're able to do number 1, it would be useful if the confirmation dialogue gave some sort of information about the actions that were performed. Would is be possible to add a counter? So it, for example, would say: 

Double space to single space
47 double spaces were removed. [Example of a counter]
What would you like to do with the revised text?
Insert [request 1 above]
Copy to clipboard
Close without doing anything

3) It's annoying that the confirmation dialogue does not respond to keyboard inputs other than enter. For example, I would like to be able to down arrow and hit enter to "Close without doing anything" or be able to hit escape, or command+backspace to do the same. Not sure that's something you control though, perhaps that's feedback I should be giving to the Alfred team?

Anyway, just my thoughts. Keep up the great work!

**Comment by Stephen-Lon** [comment]
Thanks for the comments. Quick responses are:

1. The original text should be on the clipboard (because that is how Alfred deals with it) and should be capable of being retrieved through Alfred's keyboard history feature. I think the work of the workflow has to be done with text on the clipboard using this sort of workflow. Anything else (insert directly) would require much more complex programming (probably relying on some language rather than simply Alfred Actions).
2. That is much more of a challenge and may be well above my pay grade (i.e., I'm not at all sure my programming abilities are up to it!). You're unlikely to see that (from me, at least) any time soon: sorry!
3. I, too, find that frustrating but it definitely is an "Alfred thing" so feed back on the forum about the Dialog Conditional would be appropriate.

Stephen

**Comment by Stickyhavr** [comment]
Understood on all counts. Thanks.  

I'm fine with it as is, it would just be nice to have some indication of what the action did, or where the spaces had been. But I suppose if I really needed to, I could use your other workflow to send the copy to Textedit and then select all and paste between the last two items in the clipboard history to see where the changes were.  Probably, in most cases, that won't be needed anyway.

I made a feature request re the dialog: https://www.alfredforum.com/topic/18947-additional-keyboard-inputs-for-dialog-conditional-in-workflows/ in case you have any additional comments you'd like to add. :-D
